name: habib_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_conditional: ^2.0.0+1

  flutter_dotenv: ^5.1.0

  mysql1: ^0.20.0

  hooks_riverpod: ^2.4.6
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.1

  go_router: ^13.2.0

  equatable: ^2.0.5

  flutter_svg: ^2.0.10+1

  gap: ^3.0.1

  toastification: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.9

  build_runner: ^2.4.8
  riverpod_generator: ^2.3.11
  go_router_builder: ^2.4.1

flutter:

  uses-material-design: true

  assets:
    - .env
    
    - assets/icons/

  fonts:
    - family: Switzer
      fonts:
        - asset: assets/fonts/Switzer-Black.otf
        - asset: assets/fonts/Switzer-BlackItalic.otf
          style: italic
        - asset: assets/fonts/Switzer-Bold.otf
        - asset: assets/fonts/Switzer-BoldItalic.otf
          style: italic
        - asset: assets/fonts/Switzer-Extrabold.otf
        - asset: assets/fonts/Switzer-ExtraboldItalic.otf
          style: italic
        - asset: assets/fonts/Switzer-Extralight.otf
        - asset: assets/fonts/Switzer-ExtralightItalic.otf
          style: italic
        - asset: assets/fonts/Switzer-Italic.otf
          style: italic
        - asset: assets/fonts/Switzer-Light.otf
        - asset: assets/fonts/Switzer-LightItalic.otf
          style: italic
        - asset: assets/fonts/Switzer-Medium.otf
        - asset: assets/fonts/Switzer-MediumItalic.otf
          style: italic
        - asset: assets/fonts/Switzer-Regular.otf
        - asset: assets/fonts/Switzer-Semibold.otf
        - asset: assets/fonts/Switzer-SemiboldItalic.otf
          style: italic
        - asset: assets/fonts/Switzer-Thin.otf
        - asset: assets/fonts/Switzer-ThinItalic.otf
          style: italic